---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: hackathon-default-worker-bootstraptemplate
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration: {}
